### ISSUE TITLE
NPE when starting ProB2-UI

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#107]
This exception occurs on the new MacBook Pro on macOS Monterrey, making ProB2-UI not startable

java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileName()" because "object" is null
        at de.prob2.ui.beditor.BEditorView$1.toString(BEditorView.java:163)
        at de.prob2.ui.beditor.BEditorView$1.toString(BEditorView.java:160)
        at javafx.controls/javafx.scene.control.skin.ChoiceBoxSkin.getDisplayText(ChoiceBoxSkin.java:351)
        at javafx.controls/javafx.scene.control.skin.ChoiceBoxSkin.updateLabelText(ChoiceBoxSkin.java:346)
        at javafx.controls/javafx.scene.control.skin.ChoiceBoxSkin.initialize(ChoiceBoxSkin.java:341)
        at javafx.controls/javafx.scene.control.skin.ChoiceBoxSkin.<init>(ChoiceBoxSkin.java:147)
        at javafx.controls/javafx.scene.control.ChoiceBox.createDefaultSkin(ChoiceBox.java:493)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
        at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
        at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9456)
        at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:572)
        at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1774)
        at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:396)
        at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
        at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1114)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1190)
        at javafx.graphics/javafx.stage.Window.show(Window.java:1205)
        at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
        at de.prob2.ui.ProB2.postStart(ProB2.java:284)
        at de.prob2.ui.ProB2.lambda$start$1(ProB2.java:224)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by favu100** [comment]
This issue is solved now
