### ISSUE TITLE
Out of Bounds Exception in Table Visualization View

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#109]
I clicked on the scroll bar in the lower-left corner of the Table Visualization view and got this exception:

```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at javafx.base/com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
        at de.prob2.ui.dynamic.table.ExpressionTableView.lambda$fillTable$2(ExpressionTableView.java:180)
        at javafx.controls/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:593)
        at javafx.controls/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
        at javafx.controls/javafx.scene.control.TableCell.updateItem(TableCell.java:646)
        at javafx.controls/javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
        at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
        at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
        at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:649)
        at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:588)
        at javafx.controls/javafx.scene.control.Control.computePrefHeight(Control.java:570)
        at javafx.graphics/javafx.scene.Parent.prefHeight(Parent.java:1037)
        at javafx.graphics/javafx.scene.layout.Region.prefHeight(Region.java:1559)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1863)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1948)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1250)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:837)
        at javafx.base/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
        at javafx.base/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:855)
        at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:549)
        at javafx.controls/javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:170)
        at javafx.controls/javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:145)
        at javafx.controls/javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:407)
        at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:576)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

After that the table visualisation view failed to work (i.e, update when selecting other categories).

**Comment by iTitus** [comment]
This also happens when clicking Min/Max-Values in the Table Visualization when having the VisB-Example-Project with a simple Machine open.

**Comment by iTitus** [comment]
This might be caused by a bug when parsing the Prolog data, I don't think this is supposed to look like that:
![image](https://user-images.githubusercontent.com/5154317/163577185-a54412a5-f35b-4561-970d-46b4be13ea0e.png)

**Comment by favu100** [comment]
It is possibly better to fix this issue in prob_prolog

**Comment by iTitus** [comment]
Can you still reproduce this?

**Comment by iTitus** [comment]
should hopefully not happen anymore
