### ISSUE TITLE
Exception when trying to replay non-existing trace

### ISSUE THREAD

**Issue by iTitus** [hhu-stups/prob-issues#115]
In The VisB-Example-Proejct the NQueens machine has a trace configured that does not exist. It is still shown in the replay list:
![image](https://user-images.githubusercontent.com/5154317/162410513-9434a5ca-26e1-4bcb-9f68-882413a389dc.png)

When trying to use the context menu and clicking "edit" or "show description" it shows a helpful error message:
![image](https://user-images.githubusercontent.com/5154317/162410799-a27eb3f1-3aa9-4264-b0a4-bed884c52b2b.png)

But when clicking "replay trace" or "check machine" it throws an exception:
```
java.lang.NullPointerException: Cannot invoke "de.prob.check.tracereplay.ReplayedTrace.withErrors(java.util.List)" because the return value of "de.prob.animator.command.ReplayTraceFileCommand.getTrace()" is null
	at de.prob.check.tracereplay.TraceReplay.replayTraceFile(TraceReplay.java:64)
	at de.prob2.ui.animation.tracereplay.TraceChecker.lambda$replayTrace$4(TraceChecker.java:95)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The same error message should be shown there.

**Comment by iTitus** [comment]
Fix is in dev branch
