### ISSUE TITLE
MissingResourceException in VO Manager

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#120]
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Validation task with given id is not valid
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
        at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:558)
        at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
        at de.prob2.ui.internal.StageManager.makeAlert(StageManager.java:291)
        at de.prob2.ui.internal.StageManager.makeAlert(StageManager.java:317)
        at de.prob2.ui.vomanager.VTEditingBox.warnNotValid(VTEditingBox.java:186)
        at de.prob2.ui.vomanager.VTEditingBox.applyVT(VTEditingBox.java:141)
        ... 68 common frames omitted

**Comment by favu100** [comment]
This issue is solved now
