### ISSUE TITLE
Sometimes Checking Items are not added to the respective tables (LTL View, Symbolic Checking, Model Checking)

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#13]
This issue was expected to be already fixed. But sometimes it could happen that a checking item is not added to the respective tables.

**Comment by favu100** [comment]
It seems that this issue only appears if an exception was thrown before

**Comment by favu100** [comment]
This bug only occurs when an exception was thrown in JavaFX before.

java.lang.NullPointerException: Cannot bind to null
        at javafx.base/javafx.beans.property.ObjectPropertyBase.bind(ObjectPropertyBase.java:165)
        at de.prob2.ui.verifications.ltl.LTLView.lambda$initialize$0(LTLView.java:166)
...

To reproduce this:

Modify line 165 in LTLView

//tvFormula.itemsProperty().bind(to.ltlFormulasProperty());
tvFormula.itemsProperty().bind(null);

**Comment by favu100** [comment]
We won't fix this issue because this is always caused by another error in the UI. Instead, we will fix the other errors causing this error
