### ISSUE TITLE
ConcurrentModificationException in StateView

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#130]
This error occured after loading a new machine

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at de.prob2.ui.states.StatesView.evaluateFormulaWithCaching(StatesView.java:386)
	at de.prob2.ui.states.StatesView.access$100(StatesView.java:68)
	at de.prob2.ui.states.StatesView$1.evaluate(StatesView.java:133)
	at de.prob2.ui.states.StateItem.getCurrentValue(StateItem.java:90)
	at de.prob2.ui.states.NameCell.updateItem(NameCell.java:41)
	at de.prob2.ui.states.NameCell.updateItem(NameCell.java:8)
	at javafx.controls/javafx.scene.control.TreeTableCell.updateItem(TreeTableCell.java:689)
	at javafx.controls/javafx.scene.control.TreeTableCell.lambda$new$6(TreeTableCell.java:160)
	at javafx.base/javafx.beans.WeakInvalidationListener.invalidated(WeakInvalidationListener.java:83)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.controls/javafx.scene.control.TreeTableView.setRoot(TreeTableView.java:941)
	at de.prob2.ui.states.StatesView.lambda$updateRoot$36(StatesView.java:681)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

**Comment by favu100** [comment]
This information might help: An XTL machine was loaded before

**Comment by iTitus** [comment]
A mitigation was added. Please re-open if the issue persists.
