### ISSUE TITLE
IllegalStateException: No spans have been added when double clicking on VisB warning

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#131]
When double clicking on a warning generated by VisB I got this uncaught exception:

```
java.lang.IllegalStateException: No spans have been added
        at org.fxmisc.richtext.model.StyleSpansBuilder.create(StyleSpansBuilder.java:156)
        at de.prob2.ui.beditor.BLexerSyntaxHighlighting.computeBHighlighting(BLexerSyntaxHighlighting.java:369)
        at de.prob2.ui.beditor.BEditor.computeHighlighting(BEditor.java:260)
        at de.prob2.ui.beditor.BEditor.lambda$initialize$9(BEditor.java:140)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at de.prob2.ui.beditor.BEditorView.updateErrors(BEditorView.java:229)
        at de.prob2.ui.beditor.BEditorView.lambda$initialize$3(BEditorView.java:143)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
        at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
        at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
        at de.prob2.ui.beditor.BEditorView.updateSaved(BEditorView.java:224)
...
```

**Comment by leuschel** [comment]
On the console I also see this exception:
```
[2022-04-26 18:05:47,061, 51079 ms] "pool-2-thread-1" [INFO] de.prob2.ui.beditor.BLexerSyntaxHighlighting.computeBHighlighting(BLexerSyntaxHighlighting.java:367): Failed to lex
de.be4.classicalb.core.parser.lexer.LexerException: [1,1] Unknown token: {
        at de.be4.classicalb.core.parser.lexer.Lexer.getToken(Lexer.java:4462)
        at de.be4.classicalb.core.parser.lexer.Lexer.next(Lexer.java:82)
        at de.prob2.ui.beditor.BLexerSyntaxHighlighting.computeBHighlighting(BLexerSyntaxHighlighting.java:362)
        at de.prob2.ui.beditor.BEditor.computeHighlighting(BEditor.java:260)
        at de.prob2.ui.beditor.BEditor.access$100(BEditor.java:51)
        at de.prob2.ui.beditor.BEditor$1.call(BEditor.java:246)
        at de.prob2.ui.beditor.BEditor$1.call(BEditor.java:243)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by leuschel** [comment]
When reloading the B machine in ProB2-UI I then get this exception:
```
java.lang.NullPointerException: Cannot invoke "de.prob2.ui.visb.visbobjects.VisBVisualisation.getVisBSVGObjects()" because "visBVisualisation" is null
        at de.prob2.ui.visb.VisBStage.updateDynamicSVGObjects(VisBStage.java:311)
        at de.prob2.ui.visb.VisBStage.lambda$initialize$13(VisBStage.java:214)
        at de.prob2.ui.visb.VisBStage$1.changed(VisBStage.java:390)
        at de.prob2.ui.visb.VisBStage$1.changed(VisBStage.java:378)
```

**Comment by favu100** [comment]
The last exception should be fixed now

**Comment by iTitus** [comment]
fixed by workaround: manually return empty highlighting on error.
