### ISSUE TITLE
Uncaught internal exception for JSON trace files with errors

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#135]
I adapted a JSON trace file by hand and had one comma too many.

I got this "Uncaught internal exception" dialog in ProB2-UI when trying to replay the trace
```
java.lang.NullPointerException: Cannot invoke "de.prob.check.tracereplay.ReplayedTrace.withErrors(java.util.List)" because the return value of "de.prob.animator.command.ReplayTraceFileCommand.getTrace()" is null
        at de.prob.check.tracereplay.TraceReplay.replayTraceFile(TraceReplay.java:64)
        at de.prob2.ui.animation.tracereplay.TraceChecker.lambda$replayTrace$4(TraceChecker.java:100)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by iTitus** [comment]
I thought I had fixed this, but apparently not thorough enough.

**Comment by iTitus** [comment]
should be fixed now:
![image](https://user-images.githubusercontent.com/5154317/166666761-bd63d884-571b-4bd5-9c45-acfdebc77ffa.png)
