### ISSUE TITLE
Exception when trying to invoke getParameterPredicates in Transition

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#18]
An exception is thrown when one tries to invoke getParameterPredicates on a transition with an operation name that was modeled in extended machine.

java.lang.NullPointerException: Cannot invoke "de.prob.model.classicalb.Operation.getParameters()" because "op" is null
        at de.prob.statespace.Transition.getParameterPredicates(Transition.java:239)
        at de.prob.statespace.Transition.getParameterPredicate(Transition.java:221)
        at de.prob2.ui.simulation.simulators.ProbabilityBasedSimulator.executeNextOperation(ProbabilityBasedSimulator.java:148)
        at de.prob2.ui.simulation.simulators.AbstractSimulator.executeOperation(AbstractSimulator.java:149)
        at de.prob2.ui.simulation.simulators.AbstractSimulator.executeOperations(AbstractSimulator.java:141)
        at de.prob2.ui.simulation.simulators.AbstractSimulator.simulationStep(AbstractSimulator.java:111)
        at de.prob2.ui.simulation.simulators.Simulator.simulate(Simulator.java:39)
        at de.prob2.ui.simulation.simulators.Scheduler.lambda$run$1(Scheduler.java:53)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by favu100** [comment]
This issue should be fixed now
