### ISSUE TITLE
Exception when GOAL in Model Checking is invalid

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#201]
Caused by: java.lang.IllegalArgumentException: Model checking goal must be a predicate, not EXPRESSION
    at de.prob.check.ModelCheckingOptions.customGoal(ModelCheckingOptions.java:234)
    at de.prob2.ui.verifications.modelchecking.ModelCheckingItem.getFullOptions(ModelCheckingItem.java:152)
    at de.prob2.ui.verifications.modelchecking.Modelchecker.startNextCheckStep(Modelchecker.java:88)
    at de.prob2.ui.verifications.modelchecking.ModelcheckingView.checkSingleItem(ModelcheckingView.java:235)
    at de.prob2.ui.verifications.modelchecking.ModelcheckingView.addModelCheck(ModelcheckingView.java:336)
    ... 83 more

**Comment by SherinSchneider** [comment]
IllegalArgumentException of an invalid Predictae GOAL is now catched
