### ISSUE TITLE
Exception and empty editor when duplicate definition warning occurs

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#218]
When an error occurs during loading the BEditor window is empty, meaning that one cannot fix the error
in ProB2-UI and has to use an external editor.

I had this for a duplicate DEFINITION warning.
![Screenshot 2022-09-29 at 17 39 34](https://user-images.githubusercontent.com/1742246/193076353-e63a77cb-6e23-49f5-9359-780ca1cb734c.png)

**Comment by leuschel** [comment]
The error itself is maybe also problematic:
```
java.lang.NullPointerException
	at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:324)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1541)
	at de.prob2.ui.beditor.BEditorView.isCurrentEditorFile(BEditorView.java:465)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at de.prob2.ui.beditor.BEditorView.lambda$updateErrors$13(BEditorView.java:262)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.prob2.ui.beditor.BEditorView.updateErrors(BEditorView.java:263)
	at de.prob2.ui.beditor.BEditorView.lambda$initialize$4(BEditorView.java:144)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleInvalidation.fireValueChangedEvent(ListListenerHelper.java:126)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at de.prob2.ui.error.ErrorTableView.lambda$initialize$8(ErrorTableView.java:97)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleInvalidation.fireValueChangedEvent(ListListenerHelper.java:126)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at de.prob2.ui.error.ExceptionAlert.lambda$initialize$0(ExceptionAlert.java:91)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at de.prob2.ui.error.ExceptionAlert.setException(ExceptionAlert.java:135)
	at de.prob2.ui.internal.StageManager.makeExceptionAlert(StageManager.java:333)
	at de.prob2.ui.internal.StageManager.makeExceptionAlert(StageManager.java:353)
	at de.prob2.ui.project.MachineLoader.lambda$loadAsync$5(MachineLoader.java:284)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by iTitus** [comment]
I can't really reproduce the error but added some reinforcements to the `isCurrentEditorFile` method.
Do you have the version of the file that caused the error or alternatively, can you pull the newest git version and try again?

**Comment by leuschel** [comment]
The NullPointerException has disappeared and the editor window is now visible.

The problem was e.g. with SudokoEvent from visb_visualisation_examples when adding a second VISB_JSON_FILE definition in the main file.
