### ISSUE TITLE
Exception in State View

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#233]
This exception sometimes appears when changing the machine (or at least when the model's current state changes)

```
java.lang.IllegalArgumentException: Formula BVisual2Formula{stateSpace=animator0, id=1600} does not belong to the state space of the given state: animator0
    at de.prob.animator.domainobjects.BVisual2Formula.evaluateMultiple(BVisual2Formula.java:212)
    at de.prob2.ui.states.StatesView.cacheMissingFormulaValues(StatesView.java:447)
    at de.prob2.ui.states.StatesView.updateRoot(StatesView.java:661)
    at de.prob2.ui.states.StatesView.lambda$updateRootAsync$33(StatesView.java:640)
    at de.prob2.ui.internal.executor.BackgroundUpdater.lambda$execute$3(BackgroundUpdater.java:76)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by iTitus** [comment]
There were some changes to the caching behaviour recently, this might have been fixed then.
