### ISSUE TITLE
Exception for State Visualisation in ProB2-UI

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#251]
When opening eight_puzzle_v2.P in prob_examples/XTL I get this exception related to the State Visualisation tab:

```
java.lang.IllegalArgumentException: Expected a Prolog atom, but was 2 (class de.prob.prolog.term.IntegerPrologTerm)
	at de.prob.prolog.term.PrologTerm.atomToString(PrologTerm.java:102)
	at de.prob.animator.command.GetAnimationMatrixForStateCommand.lambda$processResult$2(GetAnimationMatrixForStateCommand.java:86)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at de.prob.animator.command.GetAnimationMatrixForStateCommand.processResult(GetAnimationMatrixForStateCommand.java:73)
	at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:91)
	at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:188)
	at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:59)
	at de.prob.statespace.StateSpace.execute(StateSpace.java:597)
	at de.prob2.ui.visualisation.VisualisationView.visualiseState(VisualisationView.java:162)
	at de.prob2.ui.visualisation.VisualisationView.lambda$initialize$2(VisualisationView.java:98)
	at de.prob2.ui.internal.executor.BackgroundUpdater.lambda$execute$3(BackgroundUpdater.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by dgelessus** [comment]
Fixed in hhu-stups/prob2_kernel@747400a56c7850eb2c2b6b3971c8a95646bfa3c7.
