### ISSUE TITLE
InvalidPathException in table visualization of WD POs

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#254]
When I open the table visualization of "WD POs" or "WD POs and hyps" in ProB2-UI on Windows, I get the following error:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 175: [...]\Rangierfahrt_KI.ref within DEFINITION call of position_in_new_block_backwards at Line: 25 Column: 39 until Line: 25 Column: 110 in file: [...]\definitions.def
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at java.base/java.nio.file.Path.of(Unknown Source)
	at java.base/java.nio.file.Paths.get(Unknown Source)
	at de.prob2.ui.dynamic.table.ExpressionTableView.handleSource(ExpressionTableView.java:310)
	at de.prob2.ui.dynamic.table.ExpressionTableView.access$100(ExpressionTableView.java:62)
	at de.prob2.ui.dynamic.table.ExpressionTableView$ValueItemRow.updateItem(ExpressionTableView.java:79)
	at de.prob2.ui.dynamic.table.ExpressionTableView$ValueItemRow.updateItem(ExpressionTableView.java:64)
	at javafx.scene.control.TableRow.updateItem(TableRow.java:260)
	at javafx.scene.control.TableRow.indexChanged(TableRow.java:226)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1807)
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949)
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021)
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013)
	at javafx.scene.control.skin.VirtualFlow.scrollPixels(VirtualFlow.java:1620)
	at javafx.scene.control.skin.VirtualFlow$1.handle(VirtualFlow.java:434)
	at javafx.scene.control.skin.VirtualFlow$1.handle(VirtualFlow.java:376)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene.processGestureEvent(Scene.java:1956)
	at javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2701)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$5(GlassViewEventHandler.java:543)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollEvent$6(GlassViewEventHandler.java:523)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollEvent(GlassViewEventHandler.java:522)
	at com.sun.glass.ui.View.notifyScroll(View.java:965)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by dgelessus** [comment]
Looks like the Prolog side returns some extra information in the source location string that ProB 2 UI doesn't expect, so it incorrectly parses that extra info as part of the file name. This causes errors only on Windows, because `:` is allowed in file names on Unix but not on Windows.

It would be good if the Prolog side returned the source location info in a structured format so that ProB 2 UI doesn't have to parse it from a string (which will always be fragile).

#247 is related, because it would also benefit from a better API for accessing WD POs. But other table visualisation commands also return source locations and may suffer from the same problem, so we also need a proper solution for the table visualisation API, not just a special case for the WD POs.
