### ISSUE TITLE
ProB2-UI internal exception when VisB table command has WD errors

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#255]
For the AMAN v5 M9 model I got this exception when trying to view the VisB events in the ProB2-UI table view:

```
Yes: TABLE->list([list(['SVG-ID','Event','Target']),list([bl_1,'Move_Mouse_Block(1)',165]),list([bl_2,'Move_Mouse_Block(2)',166]),list([bl_3,'Move_Mouse_Block(3)',167]),list([bl_4,'Move_Mouse_Block(4)...
11:25:45.330 [Expression Table Visualizer] DEBUG de.prob.cli.ProBConnection - get_error_messages_with_span_info(Errors),true.
11:25:45.333 [Expression Table Visualizer] DEBUG de.prob.animator.CommandProcessor - Yes: Errors->[error('function applied outside of domain (#6):  Function argument: 1, function value: {}, function: landing_sequence~',error,[error_span('',1,9,1,29)]),error('function applied outside o...
11:25:45.346 [Expression Table Visualizer] ERROR de.prob2.ui.dynamic.DynamicCommandStage - Visualization failed with ProBError
de.prob.exception.ProBError: ProB reported Errors
ProB returned error messages:
Error: function applied outside of domain (#6):  Function argument: 1, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 2, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 3, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 4, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 5, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 6, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 7, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 8, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 9, function value: {}, function: landing_sequence~ (:1:9 to 1:29)
Error: function applied outside of domain (#6):  Function argument: 10, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#6):  Function argument: 11, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#6):  Function argument: 12, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 14, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 15, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 16, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 17, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 18, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 19, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 20, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 21, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 22, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 23, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 24, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 25, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 26, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 27, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 28, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 29, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 30, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 31, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 32, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 33, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 34, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 35, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 36, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 37, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 38, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 39, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 40, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 41, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 42, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 43, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 44, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
Error: function applied outside of domain (#7):  Function argument: 45, function value: {}, function: landing_sequence~ (:1:9 to 1:30)
        at de.prob.animator.command.AbstractCommand.processErrorResult(AbstractCommand.java:119)
        at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:94)
        at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:188)
        at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:59)
        at de.prob.statespace.StateSpace.execute(StateSpace.java:597)
        at de.prob.animator.domainobjects.TableVisualizationCommand.visualize(TableVisualizationCommand.java:80)
        at de.prob2.ui.dynamic.table.ExpressionTableView.visualizeInternal(ExpressionTableView.java:237)
        at de.prob2.ui.dynamic.table.ExpressionTableView.visualizeInternal(ExpressionTableView.java:61)
        at de.prob2.ui.dynamic.DynamicCommandStage.lambda$visualize$12(DynamicCommandStage.java:344)
        at de.prob2.ui.internal.executor.BackgroundUpdater.lambda$execute$3(BackgroundUpdater.java:76)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
11:25:45.422 [JavaFX Application Thread] ERROR de.prob2.ui.ProB2 - Uncaught exception on thread Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: Out of bounds by 9. Area Length: 0
        at org.fxmisc.richtext.model.StyledDocument.getAbsolutePosition(StyledDocument.java:191)
        at org.fxmisc.richtext.GenericStyledArea.getAbsolutePosition(GenericStyledArea.java:1192)
        at de.prob2.ui.internal.ExtendedCodeArea.getClampedAbsolutePosition(ExtendedCodeArea.java:203)
        at de.prob2.ui.internal.ExtendedCodeArea.errorLocationAbsoluteStart(ExtendedCodeArea.java:207)
        at de.prob2.ui.internal.ExtendedCodeArea.addErrorHighlighting(ExtendedCodeArea.java:222)
        at de.prob2.ui.internal.ExtendedCodeArea.computeHighlighting(ExtendedCodeArea.java:268)
        at de.prob2.ui.internal.ExtendedCodeArea.reloadHighlighting(ExtendedCodeArea.java:285)
        at de.prob2.ui.internal.ExtendedCodeArea.lambda$initialize$2(ExtendedCodeArea.java:115)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
        at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
        at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
        at de.prob2.ui.dynamic.DynamicCommandStage.lambda$handleProBError$13(DynamicCommandStage.java:373)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by leuschel** [comment]
<img width="442" alt="Screenshot 2022-12-12 at 11 27 07" src="https://user-images.githubusercontent.com/1742246/207022977-a76e5d59-11fd-462a-bb76-32f92f511206.png">

**Comment by leuschel** [comment]
I get the above dialog, but I cannot click on it. It somehow always remains hidden. Even with macOS Expose I cannot get it to the front to click the OK button.

**Comment by leuschel** [comment]
The main issue seems to be:

```
at java.base/java.lang.Thread.run(Thread.java:833)
11:25:45.422 [JavaFX Application Thread] ERROR de.prob2.ui.ProB2 - Uncaught exception on thread Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: Out of bounds by 9. Area Length: 0
at org.fxmisc.richtext.model.StyledDocument.getAbsolutePosition(StyledDocument.java:191)
at org.fxmisc.richtext.GenericStyledArea.getAbsolutePosition(GenericStyledArea.java:1192)
```

**Comment by iTitus** [comment]
I do not know the cause, but I added a workaround with more aggressive clamping.
Could it be that a wrong or invalid position is being returned?
