### ISSUE TITLE
ProB2-UI Index out of bounds exception when showing replay status

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#263]
A trace could not be replayed (TR1 Mission Order) and I obtained this error.
The project is in prob_examples/examples/B/Tickets/Gruteser_LTL_Crash

java.lang.IllegalArgumentException: javafx.fxml.LoadException: 
/Users/leuschel/git_root/JAVAPROB/ui-prob2/build/resources/main/de/prob2/ui/animation/tracereplay/trace_replay_status_alert.fxml

	at de.prob2.ui.internal.StageManager.loadFXML(StageManager.java:111)
	at de.prob2.ui.internal.StageManager.loadFXML(StageManager.java:143)
	at de.prob2.ui.animation.tracereplay.ReplayedTraceStatusAlert.<init>(ReplayedTraceStatusAlert.java:47)
	at de.prob2.ui.animation.tracereplay.TraceReplayErrorAlert.handleAlert(TraceReplayErrorAlert.java:157)
	at de.prob2.ui.animation.tracereplay.TraceReplayErrorAlert.setErrorMessage(TraceReplayErrorAlert.java:121)
	at de.prob2.ui.animation.tracereplay.TraceChecker.lambda$showTraceReplayCompleteFailed$6(TraceChecker.java:142)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: javafx.fxml.LoadException: 
/Users/leuschel/git_root/JAVAPROB/ui-prob2/build/resources/main/de/prob2/ui/animation/tracereplay/trace_replay_status_alert.fxml

	at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at de.prob2.ui.internal.StageManager.loadFXML(StageManager.java:109)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
	... 12 more
Caused by: java.lang.IndexOutOfBoundsException
	at com.github.krukow.clj_lang.PersistentVector.arrayFor(PersistentVector.java:126)
	at com.github.krukow.clj_lang.PersistentVector.nth(PersistentVector.java:130)
	at com.github.krukow.clj_lang.APersistentVector.get(APersistentVector.java:175)
	at de.prob2.ui.animation.tracereplay.ReplayedTraceStatusAlert.initialize(ReplayedTraceStatusAlert.java:84)
	... 23 more

**Comment by iTitus** [comment]
fixed with more checks.
It could be that ProB does not replay anything or it replays fewer transition than defined in the JSON.
