### ISSUE TITLE
Exception when showing trace replay status

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#276]
When I try to show the replay status of a trace in ProB2-UI (snapshot) on Windows, I get the following exception.

```
java.lang.NullPointerException: Cannot invoke "de.prob2.ui.animation.tracereplay.ReplayedTraceRow.getStyleClasses()" because "rowItem" is null
	at de.prob2.ui.animation.tracereplay.ReplayedTraceTable$1.updateItem(ReplayedTraceTable.java:71)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:689)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:474)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.scene.control.skin.TableRowSkinBase.requestCellUpdate(TableRowSkinBase.java:701)
	at javafx.scene.control.skin.TableRowSkinBase.lambda$new$1(TableRowSkinBase.java:178)
	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:88)
	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:78)
	at javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:119)
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1807)
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1791)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2966)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2949)
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3021)
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3013)
	at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1052)
	at javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2515)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:421)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:420)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by iTitus** [comment]
fixed
