### ISSUE TITLE
ProBError occurs when loading a machine

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#305]
de.prob.exception.ProBError: Prolog said no.
    at de.prob.animator.command.AbstractCommand.processErrorResult(AbstractCommand.java:114)
    at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:94)
    at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:188)
    at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:59)
    at de.prob.statespace.StateSpace.execute(StateSpace.java:721)
    at de.prob.statespace.State.explore(State.java:461)
    at de.prob.statespace.State.exploreIfNeeded(State.java:489)
    at de.prob.statespace.State.isInvariantOk(State.java:384)
    at de.prob2.ui.statusbar.StatusBar.getErrorMessages(StatusBar.java:137)
    at de.prob2.ui.statusbar.StatusBar.update(StatusBar.java:114)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by dgelessus** [comment]
Original reporter couldn't reproduce this anymore when starting the latest version from source.
