### ISSUE TITLE
Missing file leading to various errors 

### ISSUE THREAD

**Issue by yutak001** [hhu-stups/prob-issues#308]
When I used the VisB examples project for ProB2UI and clicked on einsteins_enum.als (which is not existent anymore), 3 error alerts are raised:

First (has been fixed by me, will be pushed soon):
![First Error](https://user-images.githubusercontent.com/19926137/236240500-b83ec0b2-05f2-4fa8-ae50-26898d65fcac.png)

Second:
![Second Error](https://user-images.githubusercontent.com/19926137/236239897-c2de3120-7aef-4910-b241-019c1131dd66.png)
>de.prob.exception.ProBError: ProB returned error messages:
Error: File cannot be found.
/home/shogun/Dokumente/Eclipse - Workspace/visb-visualisation-examples/Einstein/einsteins_enum.als (Datei oder Verzeichnis nicht gefunden) (:1:1)
	at de.prob.scripting.AlloyFactory.extract(AlloyFactory.java:44)
	at de.prob2.ui.project.MachineLoader.loadInternal(MachineLoader.java:303)
	at de.prob2.ui.project.MachineLoader.load(MachineLoader.java:346)
	at de.prob2.ui.project.MachineLoader.lambda$loadAsync$6(MachineLoader.java:260)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at de.prob2.ui.internal.executor.CompletableFutureTask.run(CompletableFutureTask.java:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: de.hhu.stups.alloy2b.translation.Alloy2BParserErr: File cannot be found.
/home/shogun/Dokumente/Eclipse - Workspace/visb-visualisation-examples/Einstein/einsteins_enum.als (Datei oder Verzeichnis nicht gefunden)
	at de.hhu.stups.alloy2b.translation.Alloy2BParser.parseFromFile(Alloy2BParser.kt:111)
	at de.prob.scripting.AlloyFactory.extract(AlloyFactory.java:40)
	... 9 more
Caused by: Syntax error:
File cannot be found.
/home/shogun/Dokumente/Eclipse - Workspace/visb-visualisation-examples/Einstein/einsteins_enum.als (Datei oder Verzeichnis nicht gefunden)
	at edu.mit.csail.sdg.parser.CompUtil.parseEverything_fromFile(CompUtil.java:362)
	at de.hhu.stups.alloy2b.translation.Alloy2BParser.parseFromFile(Alloy2BParser.kt:101)
	... 10 more
Caused by: java.io.FileNotFoundException: /home/shogun/Dokumente/Eclipse - Workspace/visb-visualisation-examples/Einstein/einsteins_enum.als (Datei oder Verzeichnis nicht gefunden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at edu.mit.csail.sdg.alloy4.Util.readAll(Util.java:258)
	at edu.mit.csail.sdg.parser.CompParser.alloy_parseStream(CompParser.java:2253)
	at edu.mit.csail.sdg.parser.CompUtil.parse(CompUtil.java:451)
	at edu.mit.csail.sdg.parser.CompUtil.parseRecursively(CompUtil.java:214)
	at edu.mit.csail.sdg.parser.CompUtil.parseEverything_fromFile(CompUtil.java:358)
	... 11 more

Third:
![Third Error](https://user-images.githubusercontent.com/19926137/236239360-d3952ed7-44fb-4104-be87-d1918d91e396.png)
> java.lang.IllegalArgumentException: cannot compare current file with empty path
	at de.prob2.ui.beditor.BEditorView.isCurrentEditorFile(BEditorView.java:451)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at de.prob2.ui.beditor.BEditorView.lambda$updateErrors$13(BEditorView.java:252)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.prob2.ui.beditor.BEditorView.updateErrors(BEditorView.java:253)
	at de.prob2.ui.beditor.BEditorView.lambda$initialize$4(BEditorView.java:136)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleInvalidation.fireValueChangedEvent(ListListenerHelper.java:126)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at de.prob2.ui.error.ErrorTableView.lambda$initialize$8(ErrorTableView.java:100)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$SingleInvalidation.fireValueChangedEvent(ListListenerHelper.java:126)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at de.prob2.ui.error.ExceptionAlert.createAndShowExceptionMessage(ExceptionAlert.java:96)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at de.prob2.ui.error.ExceptionAlert.setException(ExceptionAlert.java:144)
	at de.prob2.ui.internal.StageManager.makeExceptionAlert(StageManager.java:333)
	at de.prob2.ui.internal.StageManager.makeExceptionAlert(StageManager.java:353)
	at de.prob2.ui.project.MachineLoader.lambda$loadAsync$5(MachineLoader.java:284)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:833)

First one has been fixed by me and will be pushed soon. Second and third one are a bit trickier though.

**Comment by iTitus** [comment]
related to #218 and various discussions in mattermost
and commits:
[d3e5033180a16ece09352964e6abf493c1409c0d](https://github.com/hhu-stups/prob2_ui/commit/d3e5033180a16ece09352964e6abf493c1409c0d) to [99f683c1bfa5e70ab9ae036f76d99f0c42122f14](https://github.com/hhu-stups/prob2_ui/commit/99f683c1bfa5e70ab9ae036f76d99f0c42122f14)

**Comment by iTitus** [comment]
I fixed another bug in https://github.com/hhu-stups/prob2_ui/commit/8c418ff15dfe33f40b7180bd152929246de30706

-> now shows the better error again when the machine file is missing, with confirmation for removal
