### ISSUE TITLE
Exception during SimB Simulation

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#356]
I got the following exception during a SimB (external) simulation:
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:337)
	at java.base/java.util.LinkedHashSet.<init>(LinkedHashSet.java:182)
	at de.prob.statespace.Trace.getNextTransitions(Trace.java:416)
	at de.prob2.ui.operations.OperationsView.updateBG(OperationsView.java:392)
	at de.prob2.ui.operations.OperationsView.lambda$update$12(OperationsView.java:386)
	at de.prob2.ui.internal.executor.BackgroundUpdater.lambda$execute$3(BackgroundUpdater.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by dgelessus** [comment]
Should be fixed with hhu-stups/prob2_kernel@aa52f70536b0e18a69759d9e73803c228a2fd8ca.
