### ISSUE TITLE
SETUP_CONSTANTS not executed in ProB2-UI when initialisation fails

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#361]
When the INITITIALISATION fails then SETUP_CONSTANTS is not executed in ProB2-UI.
Also, after manually going forward, one cannot execute the INITIALISATION by predicate
(to obtain a visualisation of why it fails).

Example model:
```
MACHINE InitIF_Fails
SETS
 ID={aa,bb}
DEFINITIONS SET_PREF_TRACE_INFO == TRUE
CONSTANTS iv
PROPERTIES
 iv = aa
VARIABLES xx,yy
INVARIANT
 xx:ID & yy:ID
INITIALISATION 
   xx:=iv ;
   IF xx=iv THEN yy :: {iv}-{xx} 
            ELSE yy := iv END
END
```

![Screenshot 2024-08-19 at 14 20 03](https://github.com/user-attachments/assets/2f0bd814-9963-48b9-813e-b9cb05a2b2bd)
![Screenshot 2024-08-19 at 14 20 22](https://github.com/user-attachments/assets/1533db9d-4a1f-451f-a9d2-f0e4228e3940)
The Compute Unsat Core command analyses the PROPERTIES, not the INITIALISATION here.

**Comment by iTitus** [comment]
`SETUP_CONSTANTS` fails with the following (uncaught) error:
```
de.prob.exception.ProBError: ProB reported Errors
ProB returned error messages:
Error: Initialisation statement fails:  yy :: {iv} - {xx} (...\InitIF_Fails.mch:14:17 to 14:33)
	at de.prob.animator.command.AbstractCommand.processErrorResult(AbstractCommand.java:123)
	at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:197)
	at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:189)
	at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:60)
	at de.prob.statespace.StateSpace.execute(StateSpace.java:703)
	at de.prob.animator.IAnimator.execute(IAnimator.java:35)
	at de.prob.statespace.State.explore(State.java:469)
	at de.prob.statespace.State.exploreIfNeeded(State.java:506)
	at de.prob.statespace.Trace.add(Trace.java:197)
	at de.prob2.ui.operations.OperationsView.lambda$executeOperationIfPossible$11(OperationsView.java:370)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at de.prob2.ui.internal.executor.CompletableFutureTask.run(CompletableFutureTask.java:40)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

After that one can click `SETUP_CONSTANTS` again and the error popup is not shown again.
But the `No valid constants/initialisation found` warning is shown.

So this could also be a Prolog or Kernel problem?

**Comment by leuschel** [comment]
The initalisation failure errors are now added as state errors. This partly solves this problem.

There is still a small issues that: 1) we show the compute unsat core button (which debugs the PROPERTIES), 2) we do not specify exactly to the user whether it is constants/initialisation that fails, 3) we show a list of disabled events (even though only INITIALISATION should be shown as disabled).
For 1) we could either remove the button for INITIALISATION or adapt it to extract the span_predicate from the state_error or similar.

![Screenshot 2024-08-23 at 15 13 42](https://github.com/user-attachments/assets/374a6e0b-0ee9-4e2b-b133-f53f61db0983)

**Comment by leuschel** [comment]
In ProB Tcl/Tk this now looks like this:

![Screenshot 2024-08-23 at 15 14 10](https://github.com/user-attachments/assets/bc8755c8-33b0-4187-bcd2-3219b8d84c4c)
After clicking on the state error:
![Screenshot 2024-08-23 at 15 14 35](https://github.com/user-attachments/assets/a9144b3a-6705-46fc-8856-93013434cbb2)
and then clicking on visualise:
![Screenshot 2024-08-23 at 15 14 52](https://github.com/user-attachments/assets/a6129017-c752-4123-bceb-d91315b4edbb)
