### ISSUE TITLE
Spurious ProB2-UI Exception

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#364]
I just had this exception, I selected New Project and navigated but then changed my mind and cancelled.
Not sure exactly at what time the exception appeared and if it was really related to what I was doing:

```
java.lang.NullPointerException: Cannot invoke "com.sun.javafx.text.TextRun.getEnd()" because "<local18>" is null
	at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1227)
	at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:231)
	at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:257)
	at javafx.graphics@22.0.2/javafx.scene.text.TextFlow.computePrefHeight(TextFlow.java:285)
	at javafx.graphics@22.0.2/javafx.scene.Parent.prefHeight(Parent.java:1041)
	at javafx.graphics@22.0.2/javafx.scene.layout.Region.prefHeight(Region.java:1552)
	at org.fxmisc.richtext.ParagraphBox.computePrefHeight(ParagraphBox.java:246)
	at javafx.graphics@22.0.2/javafx.scene.Parent.prefHeight(Parent.java:1041)
	at javafx.graphics@22.0.2/javafx.scene.layout.Region.prefHeight(Region.java:1552)
	at org.fxmisc.flowless.VerticalHelper.prefLength(OrientationHelper.java:262)
	at org.fxmisc.flowless.OrientationHelper.prefLength(OrientationHelper.java:53)
	at org.fxmisc.flowless.SizeTracker.lambda$new$2(SizeTracker.java:79)
	at org.reactfx.collection.DynamicallyMappedList.get(MappedList.java:89)
	at org.reactfx.collection.MemoizationListImpl.force(MemoizationList.java:121)
	at org.fxmisc.flowless.SizeTracker.lambda$new$4(SizeTracker.java:88)
	at org.fxmisc.flowless.SizeTracker.lambda$new$6(SizeTracker.java:108)
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.SuccessionReducingStream.handleTimeout(SuccessionReducingStream.java:73)
	at org.reactfx.util.FxTimer.lambda$restart$0(FxTimer.java:89)
	at javafx.graphics@22.0.2/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at javafx.graphics@22.0.2/com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.graphics@22.0.2/javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.graphics@22.0.2/javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at javafx.graphics@22.0.2/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics@22.0.2/javafx.animation.Animation.doTimePulse(Animation.java:1254)
	at javafx.graphics@22.0.2/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:208)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@22.0.2/javafx.animation.Animation$1.timePulse(Animation.java:207)
	at javafx.graphics@22.0.2/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at javafx.graphics@22.0.2/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics@22.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:594)
	at javafx.graphics@22.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:578)
	at javafx.graphics@22.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:571)
	at javafx.graphics@22.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@22.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by iTitus** [comment]
Looks like a problem with JavaFX, ReactFX or FxMisc's Flowless.

**Comment by iTitus** [comment]
I had a similar, but different exception just now:
```
java.lang.NullPointerException: Cannot invoke "com.sun.javafx.text.TextLine.getStart()" because "<local14>" is null
    at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1323)
    at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:231)
    at javafx.graphics@22.0.2/com.sun.javafx.text.PrismTextLayout.getCaretShape(PrismTextLayout.java:317)
    at javafx.graphics@22.0.2/javafx.scene.text.TextFlow.caretShape(TextFlow.java:218)
    at org.fxmisc.richtext.TextFlowExt.getCaretShape(TextFlowExt.java:56)
    at org.fxmisc.richtext.ParagraphText.updateSingleCaret(ParagraphText.java:329)
    at org.fxmisc.richtext.ParagraphText.lambda$new$3(ParagraphText.java:137)
    at javafx.base@22.0.2/com.sun.javafx.collections.SetListenerHelper$SingleChange.fireValueChangedEvent(SetListenerHelper.java:161)
    at javafx.base@22.0.2/com.sun.javafx.collections.SetListenerHelper.fireValueChangedEvent(SetListenerHelper.java:70)
    at javafx.base@22.0.2/com.sun.javafx.collections.ObservableSetWrapper.callObservers(ObservableSetWrapper.java:128)
    at javafx.base@22.0.2/com.sun.javafx.collections.ObservableSetWrapper.add(ObservableSetWrapper.java:269)
    at org.fxmisc.richtext.GenericStyledArea.lambda$createCell$59(GenericStyledArea.java:1940)
    at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    at org.reactfx.EventStreams$26.tryEmit(EventStreams.java:571)
    at org.reactfx.EventStreams$26.lambda$observeInputs$1(EventStreams.java:566)
    at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
    at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
    at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
    at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
    at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
    at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
...
    at javafx.graphics@22.0.2/javafx.scene.Parent.layout(Parent.java:1208)
    at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
    at javafx.graphics@22.0.2/javafx.scene.Parent.layout(Parent.java:1208)
    at org.fxmisc.flowless.VirtualFlow.visibleCells(VirtualFlow.java:230)
    at org.fxmisc.richtext.GenericStyledArea.<init>(GenericStyledArea.java:811)
    at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:33)
    at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:45)
    at org.fxmisc.richtext.InlineCssTextArea.<init>(InlineCssTextArea.java:34)
    at org.fxmisc.richtext.InlineCssTextArea.<init>(InlineCssTextArea.java:26)
    at de.prob2.ui.output.PrologOutput.<init>(PrologOutput.java:19)
    at de.prob2.ui.output.PrologOutput$$FastClassByGuice$$1e12a35.GUICE$TRAMPOLINE(<generated>)
    at de.prob2.ui.output.PrologOutput$$FastClassByGuice$$1e12a35.apply(<generated>)
...
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
    at de.prob2.ui.ProB2.lambda$startInBackground$6(ProB2.java:242)
...
    at java.base/java.lang.Thread.run(Thread.java:1583)
```
