### ISSUE TITLE
TLA2B: Recursive definitions not supported (in Zookeeper model)

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#367]
For the Zab.tla model from
https://github.com/Lingzhi-Ouyang/Remix/tree/master/apache-zookeeper-3.9.1/zookeeper-specifications/protocol-spec
(also in prob_examples/public_examples/TLA/Zookeeper)
we have an exception:
```
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module TLC
Semantic processing of module Zab
Detected TLA+ Default Definition Spec for Clause: INITIALISATION+OPERATIONS
Detected TLA+ Default Definition Init for Clause: INITIALISATION
Detected TLA+ Default Definition Next for Clause: OPERATIONS
No default Invariant detected
Using TLA+ Spec to determine B INITIALISATION and OPERATIONS
Exception in thread "main" java.lang.RuntimeException: Should not appear.
	at de.tla2b.analysis.AbstractASTVisitor.visitExprOrOpArgNode(AbstractASTVisitor.java:40)
	at de.tla2b.analysis.AbstractASTVisitor.visitUserDefinedNode(AbstractASTVisitor.java:159)
	at de.tla2b.translation.UsedDefinitionsFinder.visitUserDefinedNode(UsedDefinitionsFinder.java:78)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:102)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.translation.UsedDefinitionsFinder.visitUserDefinedNode(UsedDefinitionsFinder.java:90)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:102)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.translation.UsedDefinitionsFinder.visitUserDefinedNode(UsedDefinitionsFinder.java:90)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:102)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprOrOpArgNode(AbstractASTVisitor.java:38)
	at de.tla2b.analysis.AbstractASTVisitor.visitBuiltInNode(AbstractASTVisitor.java:132)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:94)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.translation.UsedDefinitionsFinder.visitUserDefinedNode(UsedDefinitionsFinder.java:90)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:102)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprOrOpArgNode(AbstractASTVisitor.java:38)
	at de.tla2b.analysis.AbstractASTVisitor.visitBuiltInNode(AbstractASTVisitor.java:132)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:94)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprOrOpArgNode(AbstractASTVisitor.java:38)
	at de.tla2b.analysis.AbstractASTVisitor.visitBuiltInNode(AbstractASTVisitor.java:132)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:94)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.translation.UsedDefinitionsFinder.visitUserDefinedNode(UsedDefinitionsFinder.java:90)
	at de.tla2b.analysis.AbstractASTVisitor.visitOpApplNode(AbstractASTVisitor.java:102)
	at de.tla2b.analysis.AbstractASTVisitor.visitExprNode(AbstractASTVisitor.java:48)
	at de.tla2b.translation.UsedDefinitionsFinder.<init>(UsedDefinitionsFinder.java:40)
	at de.tla2b.analysis.SpecAnalyser.start(SpecAnalyser.java:190)
	at de.tla2bAst.Translator.translate(Translator.java:220)
	at de.tla2b.TLA2B.main(TLA2B.java:63)
```

**Comment by cobizobi** [comment]
This is because recursive definitions are not yet supported. We should improve the message.
