### ISSUE TITLE
Exception when re-loading a machine

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#370]
```
java.lang.UnsupportedOperationException
	at de.prob.model.representation.ModelElementList.clear(ModelElementList.java:143)
	at de.prob2.ui.project.machines.Machine.resetStatus(Machine.java:502)
	at de.prob2.ui.project.machines.Machine.updateModifiedTimesAndResetIfChanged(Machine.java:528)
	at de.prob2.ui.prob2fx.CurrentProject.lambda$loadMachineWithoutConfirmation$2(CurrentProject.java:167)
	at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@22.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@22.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by iTitus** [comment]
fixed https://github.com/hhu-stups/prob2_ui/commit/87881988241107184fa7da2816e624e7c808af55
