### ISSUE TITLE
Exception when model checking for GOAL in ProB2-UI for XTL model

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#377]
I got this exception after checking the GOAL option in the model checking dialog and trying to start the model checking for an XTL model:

```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Model checking goal must be a predicate, not EXPRESSION
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at de.prob2.ui.internal.executor.CompletableFutureTask$1.done(CompletableFutureTask.java:31)
        at java.base/java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
        at java.base/java.util.concurrent.FutureTask.setException(FutureTask.java:250)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at de.prob2.ui.internal.executor.CompletableFutureTask.run(CompletableFutureTask.java:40)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Model checking goal must be a predicate, not EXPRESSION
        at de.prob.check.ModelCheckingOptions.customGoal(ModelCheckingOptions.java:254)
        at de.prob2.ui.verifications.modelchecking.ProBModelCheckingItem.getFullOptions(ProBModelCheckingItem.java:99)
        at de.prob2.ui.verifications.modelchecking.ProBModelCheckingItem.execute(ProBModelCheckingItem.java:187)
        at de.prob2.ui.verifications.ICliTask.lambda$execute$0(ICliTask.java:24)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        ... 4 common frames omitted
```

**Comment by iTitus** [comment]
Are you using a prolog term as the GOAL or a B predicate?

**Comment by leuschel** [comment]
I just clicked on the radio button for searching for goals.

I think ProB supports prop(X,goal) facts in XTL specs.

**Comment by leuschel** [comment]
Actually, it is still on the to-do list:

```prolog
:- use_module(bmachine,[b_get_machine_goal/1]).
node_satisfies_goal(NodeID,MODE) :- b_or_z_mode(MODE), !,
   b_get_machine_goal(Goal),
   eclipse_interface:test_boolean_expression_in_node(NodeID,Goal,'model checking GOAL').
node_satisfies_goal(NodeID,MODE) :- csp_mode(MODE),
   transition(NodeID,io(_,goal,_),_).
% TO DO: allow XTL goal_found xtl_property ?
```

**Comment by leuschel** [comment]
I have just corrected the TO DO above: you can now search for goal XTL properties (prop/2 facts) in the ProB model checker, at least it works in Tcl/Tk.

**Comment by iTitus** [comment]
Fixed in https://github.com/hhu-stups/prob2_ui/commit/bc7c5b0b
