### ISSUE TITLE
CSP does not work anymore

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#45]
This exception is thrown when opening a CSP machine:

de.prob.parser.ResultParserException: Expected operation_info(start_cspm_MAIN,[],[],true,csp,[],[],[]) to have an arity 9, but got 8
        at de.prob.parser.BindingGenerator.checkArity(BindingGenerator.java:152)
        at de.prob.parser.BindingGenerator.checkSignature(BindingGenerator.java:131)
        at de.prob.parser.BindingGenerator.getCompoundTerm(BindingGenerator.java:92)
        at de.prob.animator.command.GetMachineOperationInfosWithTypes.operationInfoFromPrologTerm(GetMachineOperationInfosWithTypes.java:39)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at de.prob.animator.command.GetMachineOperationInfosWithTypes.processResult(GetMachineOperationInfosWithTypes.java:62)
        at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:90)
        at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:154)
        at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:43)
        at de.prob.statespace.StateSpace.execute(StateSpace.java:577)
        at de.prob.statespace.LoadedMachine.getOperations(LoadedMachine.java:64)
        at de.prob.statespace.LoadedMachine.getMachineOperationInfo(LoadedMachine.java:58)
        at de.prob2.ui.operations.OperationItem.lambda$forTransitions$2(OperationItem.java:136)

**Comment by favu100** [comment]
Should be fixed now
