### ISSUE TITLE
Internal ProB exception with running LTL check with ProB 2 UI

### ISSUE THREAD

**Issue by jartanak** [hhu-stups/prob-issues#47]
I was running a simple LTL check: "G ({in_status /= waitingFinger})" where in_status is an enumerated state variable, representing the current state in a state machine. I'm expecting the check to fail, as I'm using it in-lieu of CTL support to confirm that the state is actually achievable. Several minutes into the check, with 1000s of states checked, I got this error:

java.lang.NullPointerException
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.getResult(LTLFormulaChecker.java:133)
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.checkFormula(LTLFormulaChecker.java:81)
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.lambda$checkFormula$3(LTLFormulaChecker.java:101)
	at java.base/java.lang.Thread.run(Unknown Source)

Could it be related to being out of resources at all?

Jonathan Hammond

**Comment by favu100** [comment]
Which model did you work on? IDStation_Anime_mch-authperiod.eventb? Did you use the latest ProB2-UI release, or the current SNAPSHOT version? And did you interrupt the check?

**Comment by favu100** [comment]
java.util.NoSuchElementException
	at java.base/java.util.Scanner.throwFor(Scanner.java:937)
	at java.base/java.util.Scanner.next(Scanner.java:1478)
	at de.prob.cli.ProBConnection.getAnswer(ProBConnection.java:71)
	at de.prob.cli.ProBConnection.send(ProBConnection.java:66)
	at de.prob.cli.ProBInstance.send(ProBInstance.java:81)
	at de.prob.animator.CommandProcessor.sendCommand(CommandProcessor.java:53)
	at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:60)
	at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:154)
	at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:43)
	at de.prob.statespace.StateSpace.execute(StateSpace.java:577)
	at de.prob.check.LTLChecker.execute(LTLChecker.java:46)
	at de.prob.check.CheckerBase.call(CheckerBase.java:94)
	at de.prob.check.LTLChecker.call(LTLChecker.java:12)
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.getResult(LTLFormulaChecker.java:123)
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.checkFormula(LTLFormulaChecker.java:81)
	at de.prob2.ui.verifications.ltl.formula.LTLFormulaChecker.lambda$checkFormula$3(LTLFormulaChecker.java:101)
	at java.base/java.lang.Thread.run(Thread.java:832)

It seems that the connection to the ProB CLI was terminated

**Comment by dgelessus** [comment]
@favu100 I'm relatively certain that this is a different error - I've also encountered it before while doing something other than LTL checking, and the stack trace looks quite different than the one in the original comment. I've opened a separate issue for this error: #61

**Comment by leuschel** [comment]
I guess the problem could be related to resources.
The latest nightly build of ProB contains an improved LTL model checking, which detects (certain) safety properties and translates them to Büchi automata. This should maybe fix the issue.

**Comment by iTitus** [comment]
Was probably fixed by now.
