### ISSUE TITLE
Identifier Clash in VisB when using ClassicalB keywords as variables

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#97]
There are identifier clashes when the B model uses ClassicalB keywords as variable. This is caused by evaluating the Event-B expression as ClassicalB object internally (now in the ProB Prolog Kernel).

For example, the landing gear case study is implemented in Event-B using the variables front, left and right which are also ClassicalB keywords. When these variables are used as an expression in VisB, there are identifier clashes.

de.prob.exception.ProBError: ProB reported Errors
ProB returned error messages:
Error: Invalid combination of symbols: 'front' and ')'. This keyword (front) must be followed by an opening parenthesis.
 (null:1:104)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for front_door_cylinder_forcer:transform
Error: Invalid combination of symbols: 'left' and ')'. This keyword (left) must be followed by an opening parenthesis.
 (null:1:103)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for left_door_cylinder_forcer:transform
Error: Invalid combination of symbols: 'right' and ')'. This keyword (right) must be followed by an opening parenthesis.
 (null:1:104)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for right_door_cylinder_forcer:transform
Error: Invalid combination of symbols: 'front' and ')'. This keyword (front) must be followed by an opening parenthesis.
 (null:1:111)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for front_gear_cylinder_forcer:transform
Error: Invalid combination of symbols: 'left' and ')'. This keyword (left) must be followed by an opening parenthesis.
 (null:1:110)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for left_gear_cylinder_forcer:transform
Error: Invalid combination of symbols: 'right' and ')'. This keyword (right) must be followed by an opening parenthesis.
 (null:1:111)
Error: Errors occured during parsing:  parse_error
Error: Cannot parse or typecheck VisB formula for right_gear_cylinder_forcer:transform
	at de.prob.animator.command.AbstractCommand.processErrorResult(AbstractCommand.java:120)
	at de.prob.animator.AnimatorImpl.execute(AnimatorImpl.java:94)
	at de.prob.animator.ReusableAnimator.execute(ReusableAnimator.java:173)
	at de.prob.animator.ReusableAnimator$InternalAnimator.execute(ReusableAnimator.java:57)
	at de.prob.statespace.StateSpace.execute(StateSpace.java:582)
	at de.prob2.ui.visb.VisBFileHandler.constructVisualisationFromJSON(VisBFileHandler.java:41)
	at de.prob2.ui.visb.VisBController.setupVisualisation(VisBController.java:250)
	at de.prob2.ui.visb.VisBController.lambda$new$1(VisBController.java:87)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at de.prob2.ui.visb.VisBController.setVisBPath(VisBController.java:109)
	at de.prob2.ui.visb.VisBStage.loadVisBFile(VisBStage.java:397)
	at de.prob2.ui.visb.VisBStage.lambda$initialize$1(VisBStage.java:173)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Node.fireEvent(Node.java:8879)
	at javafx.controls/javafx.scene.control.Button.fire(Button.java:200)
	at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:206)
	at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:

**Comment by favu100** [comment]
This issue is fixed now
